### ISSUE TITLE
[バグ]グループを作成すると、自分自身が2つ登録されてしまう

### ISSUE THREAD

**Issue by ms2sato** [shuheiktgw/todo_list#11]
https://gyazo.com/75efd6fec66e54c529d6006e9a6a83b5

そしてこれの影響で、作成したユーザなのに、グループが編集できませぬ。

**Comment by ms2sato** [comment]
最新masterで反映されていたのでclose

**Comment by shuheiktgw** [comment]
あ,これ2重で登録されてたので修正しました!!
