### ISSUE TITLE
[コードスタイル]メソッドの引数の調整

### ISSUE THREAD

**Issue by ms2sato** [shuheiktgw/todo_list#12]
モデルのメソッドの引数で `current_user`のようにコントローラで使っていた変数名を入れている箇所がありますが、current_user が持つ意味合いが不要なところではその名前は不適切ですね。

`user` のように型と同じ名前にしておくのがセオリーなので、合わせてしまいましょう。

**Comment by shuheiktgw** [comment]
修正しました!

**Comment by ms2sato** [comment]
@shuheiktgw LaunchEngineに書いたけど、書き運用でやりましょう。

実際の開発に合わせて、Issueで仕事を管理しましょう。 
一つのIssueに対応するブランチを作って、PRもIssueに対応させます（タイトルはIssueと同じにしてください） 
Issue → ブランチ作成 → 実装 → PR 
の流れになります。

**Comment by shuheiktgw** [comment]
なるほど! 承知しました!

**Comment by ms2sato** [comment]
@shuheiktgw レビューを受けてからマージ、というスタイルにしましょう。そうしないと私のレビューを受けずにマージされるコードが増えてしまいます。私としては修正を通して学んでもらいたいことがあるので、レビューは大事なんです。PRを作っていただければレビューします。よろしくお願いします。

**Comment by ms2sato** [comment]
@shuheiktgw すでにマージしたものは仕方ないので、次からお願いします。

**Comment by shuheiktgw** [comment]
承知しました! とりあえず今マスターで編集してしまったところまでpushしまして, 次のissueからイシューごとに別ブランチで作業します.@ms2sato

**Comment by ms2sato** [comment]
@shuheiktgw OKですー。よろしくお願いします。あと、Issueをcloseするのはoriginのmasterにマージされた後ですよ。全てが終わったらcloseします。

**Comment by shuheiktgw** [comment]
なるほどなるほど! わかりました!

**Comment by ms2sato** [comment]
よろしくどうぞー。これでだいぶ現場っぽい運用になりました。
