### ISSUE TITLE
[コードスタイル]インデント

### ISSUE THREAD

**Issue by ms2sato** [shuheiktgw/todo_list#13]
今、コードの中に、タブでのインデントと、スペースでのインデントが混ざっていると思います。
railsでは2タブ（インデントは2つのスペース）で行うことが多いので合わせましょう。

これはスタイルだけの話でもあるので、一旦「今後のコードはそれに倣う」でも良いです。

**Comment by shuheiktgw** [comment]
なるほど,ちょっとこれは「今後のコードはそれに倣う」でいきます!

**Comment by ms2sato** [comment]
いいすよ。何か直すついでに合わせましょう。
