### ISSUE TITLE
[リファクタ]Group#create_a_new_goup は Group.new を含んでクラスメソッドにするのが自然

### ISSUE THREAD

**Issue by ms2sato** [shuheiktgw/todo_list#15]
`Group.create`の亜種のようなものなので、同様のスタイルに合わせる方が分かりやすくなります。
インスタンスを作成するのはクラスメソッドの中で良いです。

テストも一緒に修正してください。

**Comment by shuheiktgw** [comment]
Group#create_a_new_goupの中に入れました! ただちょっとテストのコードが汚くなった?
