### ISSUE TITLE
[バグ]operatorがグループに入れない

### ISSUE THREAD

**Issue by ms2sato** [shuheiktgw/todo_list#18]
- [x] 実際に入れないか動作確認をする
- [x] おそらく今成功しているmember?テストが間違えているので、まず新たにテストを追加して今回の失敗ケースのテストを書く
- [x] 実装して、テストをグリーンにする

の手順で対応してください。

**Comment by shuheiktgw** [comment]
あ,間違えた

**Comment by shuheiktgw** [comment]
テスト書いて修正しました!! もっと丁寧にやらねばならない

**Comment by ms2sato** [comment]
丁寧さ大事ですね。このレベルもコントローラのテストを書くようになるとチェックできますよ。

上記の3ステップは実際に現場でもよくやります。最初に失敗テストを書くことで確実に直します。
