### ISSUE TITLE
「コントローラのテスト」を調査して、実装してみる

### ISSUE THREAD

**Issue by ms2sato** [shuheiktgw/todo_list#29]
- [ ] rspecでcontrollerのテストを調べてみましょう
- [ ] Deviseを使ったログインユーザを用いたテストの方法を調べて、テストに組み込みましょう。
- [ ] 調べたことを活用して今回のサービスのcontrollerのテストを実際に書きましょう。

新しいことを学びましょう。今コントローラのテストは放置状態になっていると思うので、これを動かしましょう、という内容です。まず一つ手をつけてみてWIPしてください。

**Comment by ms2sato** [comment]
@shuheiktgw 手が空いてしまう場合には、こちらをやりましょう！

**Comment by shuheiktgw** [comment]
夕方からこれ取り組みます!
